name: Main

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Handle Markdown
        run: npm install

      - name: Format Markdown Metadata
        run: npm run bootstrap

      - name: Prettier
        run: npm run prettier

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: 🤖 Bootstrap"
