name: Main

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Handle Markdown
        run: npm install

      - name: Format Markdown Metadata
        run: npm run bootstrap

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: 🤖 Bootstrap"
